name: Make Windows .Net

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  make:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: ['3.1.x', '5.0.x']
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Clean sh.exe
      run: |
        where sh
        rm 'C:\Program Files\Git\usr\bin\sh.exe'
        rm 'C:\Program Files\Git\bin\sh.exe'
      shell: bash
    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Check dotnet
      run: dotnet --info
    - name: Check make
      run: tools\make --version
    - name: Check system
      run: tools\make detect_port
    - name: Build third party
      run: tools\make third_party -j4
    - name: Build C++
      run: tools\make cc -j4
    - name: Build .Net
      run: tools\make dotnet -j4
    - name: Test .Net
      run: tools\make test_dotnet -j4
    - name: Create nuget packages
      run: tools\make package_dotnet
