name: Make Linux .Net

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  make:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: ['3.1.x', '5.0.x']    
    steps:
    - uses: actions/checkout@v2
    - name: Check make
      run: make --version
    - name: Swig install
      run: sudo apt install -y swig
    - name: Check swig
      run: swig -version
    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: ./
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Check dotnet
      run: dotnet --info
    - name: Build third party
      run: make third_party -j4
    - name: Build C++
      run: make cc -j4
    - name: Build .Net
      run: make dotnet -j4
    - name: Test
      run: make test_dotnet -j4
    - name: Create nuget packages
      run: make package_dotnet
