name: Make Linux Python

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  make:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install python3 venv
      run: sudo apt-get install python3-venv
    - name: Check cmake
      run: cmake --version
    - name: Swig install
      run: sudo apt install -y swig
    - name: Check swig
      run: swig -version
    - name: Update Path
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Build third party
      run: make third_party -j4
    - name: Build C++
      run: make cc -j4
    - name: Build Python
      run: make python -j4
    - name: Test
      run: make test_python -j4
    - name: Create wheel package
      run: make package_python
